Ei 47
Corporation-dok/ECONO-AI pull request #113
Opened 2024-03-05 04:10 UTC by yoounyoungheon

✅ 작업 내용
- 예측지표 도메인을 만들었습니다.
- 예측지표를 생성하는 api를 구현했습니다.
- 추가로 test시 예측지표 id로 예측지표를 불러오는 api가 필요하다고 판단해서 구현했습니다.

## 🤔 고민 했던 부분
- CustomForecastIndicator Entity에서 pk로 uuid를 설정했는데, 경호님이 하신 방식을 참고했는데 자동으로 id가 생성되지 않아 domain ceateNew 메서드에 uuid()를 설정했습니다.
- 4. Body값을 보낼 때 targetId가 지표 uuid인데 이 지표 id가 uuid인지 검증하는 파이프나 도메인 규칙이 필요할까요 ?

## 🔊 도움이 필요한 부분
- 아직 관련 도메인 메서드를 다 구현하지 않아 비즈니스 규칙을 세분화하지 못했습니다.
- 설계가 과정 중에 생각하지 못한 부분이 많아, fast api와 연동하고 재료지표와 가중치를 업데이트하는 과정에서 다시 한번 수정이 필요할 것 같습니다... (죄송합니다)
- targerId가 indicatorId에 있는지 검증하는 과정을 아직 구현하지 못했습니다. 이것도 fast api랑 연동하는 과정에서 수정하겠습니다.

- 설계를 꼼꼼히 했다고 생각했는데, 작업을 하다보니 놓친 부분과 고민할 부분이 많아서 일단 예측지표 객체만들기랑 불러오기 기능 구현에 집중했습니다. 재료지표/ 가중치update하는 기능 구현하면서 더 꼼꼼히 설계하겠습니다 ..

2024-03-05 04:44 UTC, seonghunYang requested changes
- 고생하셨습니다!

2024-03-05 04:44 UTC, seonghunYang commented on api/src/numerical-guidance/api/numerical-guidance.controller.ts
[comment]
- userId로 예측 지표 조회하는 API는 아직 없는게 맞을까요?

2024-03-05 04:44 UTC, seonghunYang commented on api/src/numerical-guidance/domain/custom-forecast-indicator.ts
> +    this.checkRule(new CustomForecastIndicatorNameShouldNotEmpty(customForecastIndicatorName));
[request change]
- 비즈니스 규칙 검사 시점은 굳이 따지자면 생성자 안이 아니라 createNew 함수 안이 맞을 것 같네요
- 규칙에 어긋나면 객체가 생성되지 않는게 맞기 때문 입니다.

2024-03-05 04:44 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/mapper/custom-forecast-indicator.mapper.ts
> +    customForecastIndicatorEntity.updatedAt = customForecastIndicator.updatedAt;
[comment]
- 이거 좀 더 이쁘게 처리할 수 있는 방법이 없을까요?
- 최소한 엔티티 팩토리 내부로 감추는게 좋아보이네요

2024-03-05 04:44 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/domain/custom-forecast-indicator.spec.ts
[request change]
- 도메인 계층에 대한 테스트가 너무 빈약해요
- 모든 테스트 계층 중 도메인 계층에 대한 테스트가 가장 많아야합니다.
- 우리 아키텍처에서 비즈니스 로직은 도메인 계층에 다 모여있기 때문이죠
- 잠깐만 생각해봐도 지표 이름 없을 때 생성이 되지 않는지를 확인하는 테스트는 왜 여기에 없을까요?

2024-03-05 05:01 UTC, Hoya324 reviewed
고생하셨습니다! 이제는 프로젝트 사이즈가 점점 커지면서 작은 컨벤션 실수라도 변경사항이 너무나 많아지는 걸 저번에 경험했습니다. 그래서 이번에 리뷰를 세세한 부분까지 했어요! 반복된다면 생각보다 중요한 사항일 수 있으니 다음에는 내 코드도 잘못된 부분을 지적해주실 수 있을 정도로 인지해주시면 좋을거 같아요!

2024-03-05 05:11 UTC, Hoya324 commented on api/src/numerical-guidance/application/port/persistence/custom-forecast-indicator/laod-custom-forecast-indicator.port.ts
[request]

파일 이름 오타 수정해주세요. 파일명 오타가 너무 잦아요..ㅜㅠㅠㅠ

2024-03-05 05:55 UTC, Hoya324 reviewed
@PrimaryGeneratedColumn('uuid') 해결 부분입니다!

2024-03-05 05:55 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/mapper/custom-forecast-indicator.mapper.ts
> +    customForecastIndicatorEntity.id = customForecastIndicator.id;
[request]

@PrimaryGeneratedColumn('uuid') 이 작동하지 않는 원인 입니다! id값이 없는 도메인 id를 entity id로 설정해둔 것이 문제였네요

2024-03-05 05:55 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/mapper/custom-forecast-indicator.mapper.ts
> +    customForecastIndicatorEntity.updatedAt = customForecastIndicator.updatedAt;
이거 indicator board metadata mapper 부분 참고하시면 될거 같습니다

2024-03-05 06:25 UTC, yoounyoungheon commented on api/src/numerical-guidance/api/dto/create-custom-forecast-indicator.dto.ts
> +  @ApiProperty({ example: '목표 지표 id', description: '목표 지표 id' })
45e299fb485854e98c3ed81ffcd47de90b731fec
네 !

2024-03-05 06:25 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/query/get-custom-forecast-indicator/get-custom-forecast-indicator.query.handler.ts
> +  async execute(getCustomForecastIndicatorQuery: GetCustomForecastIndicatorQuery): Promise<CustomForecastIndicator> {
096a4c6439e2a63797da081f1f99f7dd54657eaa
다른 핸들러도 수정했습니다 !

2024-03-05 06:28 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/custom-forecast-indicator.persistent.adapter.ts
> +          message: '[ERROR] 지표를 불러오는 중에 예상치 못한 문제가 발생했습니다.',
ab304aaf050e725c0903daf8e05f1f6a8ebd7763

2024-03-05 06:28 UTC, yoounyoungheon commented on api/src/numerical-guidance/api/numerical-guidance.controller.ts
> +    @Res() res: Response,
ab304aaf050e725c0903daf8e05f1f6a8ebd7763

2024-03-05 06:29 UTC, Hoya324 commented on api/src/numerical-guidance/api/dto/create-custom-forecast-indicator.dto.ts
> +  @ApiProperty({ example: '목표 지표 id', description: '목표 지표 id' })
아뇨아뇨 0d73cea1-35a5-432f-bcd1-27ae3541ba60 이런식으로 진짜 id를 넣어주세요

2024-03-05 06:30 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/custom-forecast-indicator.persistent.adapter.ts
> +          message: '[ERROR] 예측지표를 불러오는 중 오류가 발생했습니다. 잘못된 요청입니다.',
ab304aaf050e725c0903daf8e05f1f6a8ebd7763

2024-03-05 06:32 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/persistence/custom-forecast-indicator.persistent.adapter.spec.ts
> +      '목표지표 uuid',
131d5a372f79552ebd056dac59ba2dc35c8de94f

2024-03-05 06:34 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/persistence/custom-forecast-indicator.persistent.adapter.spec.ts
> +      '목표지표 uuid',
cc5cadfe1b706a2fbd621a656d16349a6654cb1e

2024-03-05 06:34 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/unit-test/domain/custom-forecast-indicator.spec.ts
> +    const customForecastIndicator = CustomForecastIndicator.createNew('예측지표 이름', '목표지표 uuid');
131d5a372f79552ebd056dac59ba2dc35c8de94f

2024-03-05 06:35 UTC, yoounyoungheon commented on api/src/utils/type/type-definition.d.ts
> +export type IndicatorType = 'k-stock' | 'exchange' | 'CustomForecastIndicator';
934ef437800042f2048a8be850e2bf39d9ddd1ab

2024-03-05 06:36 UTC, yoounyoungheon commented on api/src/utils/type/type-definition.d.ts
> +  Weight: float;
c61476ef5519d355e64619ab25dea27179a21125

2024-03-05 06:36 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/port/persistence/custom-forecast-indicator/laod-custom-forecast-indicator.port.ts
778b9b10c3bedb9081c7f66aab2f338e4ee65a7a

2024-03-05 06:41 UTC, yoounyoungheon commented on api/src/numerical-guidance/api/dto/create-custom-forecast-indicator.dto.ts
> +  @ApiProperty({ example: '목표 지표 id', description: '목표 지표 id' })
468dfc94bc520cc8bee74640ad1e2e10bdfdb1b4 넵 !

2024-03-05 06:54 UTC, yoounyoungheon commented on api/src/numerical-guidance/domain/custom-forecast-indicator.ts
> +    const id = uuid();
529365d748e2b9abe456681d0d4fdcf31649e3b0 감사합니다 !

2024-03-05 09:56 UTC, yoounyoungheon commented on api/src/numerical-guidance/domain/custom-forecast-indicator.ts
> +    this.checkRule(new CustomForecastIndicatorNameShouldNotEmpty(customForecastIndicatorName));
그렇게 되면 createNew 함수를 정적 메서드로 선언하지 못하는데 괜찮을까요 ? 경호님 indicator-board-metadata에도 같은 로직으로 되어있어 고민하다가 질문드립니다 !

2024-03-06 07:07 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/mapper/custom-forecast-indicator.mapper.ts
> +    customForecastIndicatorEntity.updatedAt = customForecastIndicator.updatedAt;
24c60ada31322369dedccf7ea9703e36448914bf
entity facotry method로 createNew함수 생성했습니다!

2024-03-06 07:25 UTC, yoounyoungheon commented on api/src/numerical-guidance/api/numerical-guidance.controller.ts
네 바로 이어서 작업하겠습니다 !

2024-03-06 07:42 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/entity/custom-forecast-indicator.entity.ts
> +  sourceIndicatorIdsAndWeights: SourceIndicatorIdAndWeightType[];
popstgresql에 json 포멧을 저장할 때 사용하는 자료형입니다. sourceIndicatorIdsAndWeights: [
		{
			변경할id: '160e5499-4925-4e38-bb00-8ea6d8056484',
		  weight: 0.7
	  },
	  {
			변경할id: '160e5499-4925-4e38-bb00-8ea6d8056484',
			weight: 0.7
	  },
	  {
			변경할id: '160e5499-4925-4e38-bb00-8ea6d8056484',
	    weight: 0.7
	  },
  ] 예측지표 객체 중 sourceIndicatorIdsAndWeights가 저장되어야 할 포멧을 찾아보다가 enum과 record중 jsonb형식이 제일 맞겠다고 판단했습니다. 참고한 자료: https://americanopeople.tistory.com/300

2024-03-06 13:05 UTC, seonghunYang commented on api/src/numerical-guidance/domain/custom-forecast-indicator.ts
> +    this.checkRule(new CustomForecastIndicatorNameShouldNotEmpty(customForecastIndicatorName));
음 좀 더 자세히 설명해주실래요?  createNew 함수에 비즈니스 규칙을 적용하는 것이랑 정적 메서드로 선언하는게 어떤 관계죠?

2024-03-06 16:18 UTC, yoounyoungheon commented on api/src/numerical-guidance/domain/custom-forecast-indicator.ts
> +    this.checkRule(new CustomForecastIndicatorNameShouldNotEmpty(customForecastIndicatorName));
checkrule 메서드가 CustomAggregateRoot라는 추상 클래스에 구현되어 있어 정적메서드인 createNew()에서 생성이 불가능해보입니다. 방안은 createNew()함수 내부에 checkRul 메서드를 사용하지 않고 crateNew에서 유효성을 검사해 직접 에러를 던져서 처리하는 방법이 있는데 그렇게 할까요?

2024-03-07 04:51 UTC, seonghunYang commented on api/src/numerical-guidance/domain/custom-forecast-indicator.ts
> +    this.checkRule(new CustomForecastIndicatorNameShouldNotEmpty(customForecastIndicatorName));
그렇겠네요. 좋습니다. 말씀하신대로 그러면 생성자 내부에서 checkrule을 하는게 맞겠네요. 설명 감사합니다 :)

2024-03-07 04:53 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/domain/custom-forecast-indicator.spec.ts
> +  it('예측지표생성-자표이름이 빈 값일 경우', () => {
[request change]
- 엄밀하게 말하면 다른 테스트인데, 같은 테스트명인게 어색하군요
- 테스트명을 보고도 어떤 테스트인지 알아야하는데 지금 여기서는 불가능한 것 같아요

2024-03-07 05:35 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/unit-test/domain/custom-forecast-indicator.spec.ts
> +  it('예측지표생성-자표이름이 빈 값일 경우', () => {
6a25805ba07c9ea8878b84aadba7f647ac9e68be
수정했습니다 !

2024-03-07 05:48 UTC, seonghunYang approved these changes

2024-03-07 05:49 UTC, seonghunYang approved these changes

2024-03-07 05:57 UTC, merged