EI 85 - 외부 API 연동
Corporation-dok/ECONO-AI pull request #39
Opened 2024-01-23 09:28 UTC by yoounyoungheon

2024-01-23 09:53 UTC, seonghunYang requested changes

2024-01-23 09:53 UTC, seonghunYang commented on api/package.json
> +    "test": "jest --detectOpenHandles --forceExit",
이 옵션은 뭔가요? 왜 추가한거죠?

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/krx/fluctuatingIndicator.krx.adapter.ts
> +export class FluctuatingIndicatorKrxAdapter {
여기서 port를 implement 하셔야합니다!

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/krx/fluctuatingIndicator.krx.adapter.ts
> +    const res = await lastValueFrom(
이거 pipe가 rxjs라는 함수형 프로그래밍 기법인데, 함수형 프로그래밍에 대한 이해도가 팀 전체적으로 높지 않으니까 원래대로 axiosref 이거 써서 받는게 어떨까요?

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/krx/fluctuatingIndicator.krx.adapter.ts
> +    const request_url: string = `https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo?serviceKey=f5burUfSauyza43%2F8ohdEUPRiVyXVJaN31DAiPF4bGgtif%2BdgQVtK11RWjpybFB
service key를 환경변수로 빼야할 것 같습니다

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/krx/fluctuatingIndicator.krx.adapter.ts
> +    테스트 코드의 목 데이터와 실제 API연동 데이터가 달라서 테스트 할 때마다 fail이 발생함
테스트 코드에는 그러면 값 말고, ticker 값이라던지 연동이 되는 것만 확인할 수 있게 작성하면 될 것 같습니다

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    await fluctuatingIndicatorKrxAdapter.loadFluctuatingIndicatorWithoutCache(5, '005930', 'KOSPI');
여기서는 왜 호출하죠?

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +  it('외부 API 연동 테스트', async () => {
테스트명 동작 관점으로 바뀌어야 합니다. 정상경로를 테스트하실거면 "캐시 없이 외부 API 받아오기" 같은 서술로 바뀌어야 합니다.

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    const expected = FluctuatingIndicatorsDto.create(testData);
이러면 통과하나요? 매번 바뀔 것 같은데

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/query/get-fluctuatingIndicator-without-cache.query.handler.spec.ts
> +const testData = {
테스트 데이터가 중복되니까 따로 빼야할 것 같습니다. 지금 main에 보면 test data 를 위한 폴더가 있으니까 참고하세요

2024-01-23 09:53 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/query/get-fluctuatingIndicator-without-cache.query.handler.spec.ts
> +  it('API 데이터롤 가져온다', async () => {
더 명확하게 서술 되어야합니다 무슨 API 데이터를 가져오는지 테스트명만 보고도 어떤 테스트인지 파악이 되어야합니다

2024-01-23 10:00 UTC, yoounyoungheon commented on api/package.json
> +    "test": "jest --detectOpenHandles --forceExit",
제 환경에서는 테스트할 때 "a worker process has failed to exit gracefully and has been force exited. this is likely caused by tests leaking due to improper teardown. try running with --detectopenhandles to find leaks. active timers can also cause this, ensure that .unref() was called on them." 이라는 경고 문구가 생겼습니다. 찾아보니 listen시 이벤트가 종료되지 않아 강제 종료되는 경고였습니다. 그래서  --detectOpenHandles 로 열려있는 리소스를 모두 닫아주고, --forceExit로 테스트가 끝나면 강제 종료를 해주는 옵션을 추가했습니다.

2024-01-23 10:08 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/krx/fluctuatingIndicator.krx.adapter.ts
> +    const res = await lastValueFrom(
네!

2024-01-23 10:14 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    const expected = FluctuatingIndicatorsDto.create(testData);
경호님과 의논했을 때 변동 지표를 불러오는 API테스트는 테스트할 때 마다 mok데이터와 달라져서 지금 당장 고정해둘 필요가 있다고 판단했습니다. 그래서 먼저 요청 url에 시작, 마지막 날짜를 임의로 설정해뒀습니다. 그리고 추 후 비즈니스로 요구사항에 따라 어댑터의 파라미터에 시작과 마지막 날짜를 추가하는 것을 결정하기로 했습니다.

2024-01-23 10:14 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    await fluctuatingIndicatorKrxAdapter.loadFluctuatingIndicatorWithoutCache(5, '005930', 'KOSPI');
given이 전제라서 "adapter가 호출되었을때"라고 생각해 호출해줬는데, 생각해보니 작동하지 않는 코드인 것 같습니다!

2024-01-23 10:29 UTC, seonghunYang commented on api/package.json
> +    "test": "jest --detectOpenHandles --forceExit",
https://bba-dda.tistory.com/113

2024-01-24 04:06 UTC, yoounyoungheon commented on api/package.json
> +    "test": "jest --detectOpenHandles --forceExit",
bdd191376c86396242b0a18554225659d993d1a4 스크립트 수정입니다

2024-01-24 04:16 UTC, seonghunYang requested changes

2024-01-24 04:16 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +  it('캐시 없이 외부 데이터 가져오기', async () => {
count 6으로 줬을 때 올바른 개수가 나오는지 확인

2024-01-24 04:20 UTC, seonghunYang submitted a review, later dismissed

2024-01-24 04:20 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/api/dto/get-fluctuatingIndicator-without-cache.dto.ts
> +export class GetFluctuatingIndicatorsWithoutCacheDto {
indicators -> indicator

2024-01-24 04:21 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/api/numerical-guidance.controller.ts
> +  }
getFluctuatingIndicatorsWithoutCache -> getFluctuatingIndicatorWithoutCache 로 바꿔주시고 dto도 마찬가지로 바꿔주시면 될거 같습니다! 이 부분은 따로 rename commit 으로 바꿔주세요!

2024-01-24 04:56 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/krx/fluctuatingIndicator.krx.adapter.ts
> +  async loadFluctuatingIndicatorWithoutCache(
ae09636184b120b3ef59a02906fb1db5ee4b8a06 완료했습니다!

2024-01-24 05:20 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/api/numerical-guidance.controller.ts
> +  }
6ce329479908da1a063202ae329e10e40ba60a45 완료했습니다!

2024-01-24 07:53 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +  it('캐시 없이 외부 데이터 가져오기', async () => {
29216108bdaffe4085005524ee5ea660e6c4de5b 데이터 개수가 올바른지 확인하는 테스트와 시장을 KOSDAQ으로 주었을 때 올바르게 나오는지 확인하는 테스트까지 추가했습니다!

2024-01-24 13:10 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +  it('캐시 없이 외부 데이터 가져오기', async () => {
커밋 ID가 잘못들어간 것 같긴한데, 테스트 작성한건 아주 좋네요!

2024-01-24 13:11 UTC, seonghunYang approved these changes

2024-01-24 13:11 UTC, merged