Ei 110, interval 기능 추가
Corporation-dok/ECONO-AI pull request #46
Opened 2024-01-27 05:57 UTC by yoounyoungheon

2024-01-27 06:50 UTC, seonghunYang requested changes

2024-01-27 06:50 UTC, seonghunYang commented on api/src/numerical-guidance/application/query/get-fluctuatingIndicators/get-fluctuatingIndicators.query.handler.ts
> +  private createFluctuatingIndicatorKey(ticker: string, interval: string) {
이거 근데 여기서만 쓰일까? 유틸리티 계층 만들어서 helper 함수로 빼도 좋을 듯. 근데 이건 실제로 중복 일어날 때 해도 됨

2024-01-27 06:50 UTC, seonghunYang commented on api/src/numerical-guidance/numerical-guidance.module.ts
> +        timeout: 10000,
이거 timeout은 뭔가요?

2024-01-27 06:50 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    for (let i = 0; i < items.length; i++) {
요기 부분 설명해주실 수 있을까요? 설명한 내용 주석으로 달아놔도 좋을 것 같아요

2024-01-27 06:50 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +      'day',
day로 가져와서 week로 만드는 것 같은데 혹시 test 시간은 얼마나 걸리나요?

2024-01-27 06:50 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    const items = dayResponseData.items.item;
**private이라서 이렇게 로직을 빼서 또 만드신가죠?
너무 test가 복잡해져서 해결 방법은 생각해봐야할 것 같아요 제가 생각한건 2가지입니다.
1. 변환 로직을 유틸함수로 분리한다
2. krx에 종속되어서 adpater에 존재해야한다면 정적 메소드로 만든다.
경호랑 영헌씨랑 이야기해보고 더 나은 방향 있다면 해도됩니다. 지금은 로직이 중복으로 있어서 테스트가 너무 깨지기 쉬워 통합하는게 필요해요**

2024-01-27 06:53 UTC, seonghunYang requested changes

2024-01-27 06:53 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
**private이라서 이렇게 로직을 빼서 또 만드신가죠?
너무 test가 복잡해져서 해결 방법은 생각해봐야할 것 같아요 제가 생각한건 2가지입니다.

변환 로직을 유틸함수로 분리한다
krx에 종속되어서 adpater에 존재해야한다면 정적 메소드로 만든다.
경호랑 영헌씨랑 이야기해보고 더 나은 방향 있다면 해도됩니다. 지금은 로직이 중복으로 있어서 테스트가 너무 깨지기 쉬워 통합하는게 필요해요**

2024-01-27 07:23 UTC, yoounyoungheon commented on api/src/numerical-guidance/numerical-guidance.module.ts
> +        timeout: 10000,
9887408dd03ea3edb76eb7bebb0f393fc2d7db75 
axios config에서 최대 응답 대기 시간을 설정하는 인자입니다. 서버에서 응답을 요청할 때, 네트워크 문제인지 응답이 5초를 넘기는 일이 발생해서 5초에서 10초로 수정했습니다.

2024-01-27 07:25 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    for (let i = 0; i < items.length; i++) {
9887408dd03ea3edb76eb7bebb0f393fc2d7db75
주석으로 달아놔서 다시 pr올리겠습니다.

2024-01-27 07:31 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +      'day',
9887408dd03ea3edb76eb7bebb0f393fc2d7db75
33-34초 정도 걸립니다!

2024-01-27 08:12 UTC, Hoya324 commented on api/src/numerical-guidance/application/query/get-fluctuatingIndicators/get-fluctuatingIndicators.query.handler.ts
> +  private createFluctuatingIndicatorKey(ticker: string, interval: string) {
넵 중복일어날 때 분리작업할거 생각해두겠습니다!

2024-01-27 18:11 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
> +    for (let i = 0; i < items.length; i++) {
368f6deb9534cee4a8c776576fa51868adf75fd7
경호님과 상의한 후 테스트 코드 수정했습니다!

2024-01-27 18:12 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/krx/fluctuatingIndicator.krx.adapter.spec.ts
368f6deb9534cee4a8c776576fa51868adf75fd7
경호님과 상의후 테스트 코드 수정했습니다.
api 요청 매개변수에 endDate추가해서 요청값을 고정한 후 그에 맞는 데이터를 잘 계산했는지 판단하는 로직으로 변경했습니다!

2024-01-28 02:08 UTC, seonghunYang approved these changes

2024-01-28 02:08 UTC, merged