Ei 114 indicator board meta
Corporation-dok/ECONO-AI pull request #49
Opened 2024-01-30 08:26 UTC by Hoya324

## ✅ 작업 내용
- 지표보드 메타데이터를 생성하는 작업을 진행했습니다.

## 🤔 고민 했던 부분
- 기존의 mySQL은 RDB 방식으로만 데아터를 처리할 수 있어, 지표보드메타데이터 - 지표 사이의 관계를 정규화하게 될 경우 중복 값이 늘어나는 문제가 있었습니다.
- 또한 지표를 하나의 table로 만들게 될 경우 수정, 삭제가 빈번하게 일어나 성능상의 문제가 우려되는 상황이었습니다.
- 이에 noSQL을 도입하여 자유로운 Schema-less 구조를 이용하자는 의견과,  Supabase로 완전히 db에 대한 비용을 줄이자는 의견이 있었습니다.
- community를 포함한 관계가 중요한 데이터 구조가 있다고 판단했고, 익숙한 RDB를 사용하는 대신 필요한 경우에 key-value로 저장하여 최적화하고자 했습니다.
- 위의 근거를 토대로 지표보드 메타데이터의 지표 컬럼에 postgreSQL의 hstore 자료형을 사용하도록 변경했습니다.

2024-01-30 14:09 UTC, seonghunYang requested changes
- 일단 메타데이터 생성하는 유닛 테스트랑 db 연결하는 통합 테스트 없는 것 같은데 맞나? 맞으면 추가해서 다시 올려줘
- 보면서 느낀건 경호가 이제 구조랑 코드를 어떻게 구현해야할지 좀 익숙해 졌다는 느낌이 드네 굿굿
- 좀 더 익숙해지면 개선할 점 찾아서 공유하고 수정하면 좋을 듯, 나도 리뷰하면서 눈에 밟히는게 몇몇 보이긴 하는데 개발 진행이 좀 안정화되면 하나하나 고쳐나가자
- 그냥 의견은 [comment]로 수정 요청은 [request change]로 표기했어 수정 요청에만 커밋 로그 남기면 돼!
- 수정한건 내일 퇴근하고 볼게

2024-01-30 14:09 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/persistent/indicator-board-meta-data.persistent.adapter.ts
> +    const indicatorBoardMetaDataEntity: IndicatorBoardMetaDataEntity = IndicatorBoardMetaDataMapper.mapToEntity(
[requset changes]
이거 인자를 이렇게 푸는 것 보다 도메인 객체 통으로 넣는게 좋을 듯

2024-01-31 04:54 UTC, Hoya324 commented on api/src/numerical-guidance/application/query/get-fluctuatingIndicator-without-cache/get-fluctuatingIndicator-without-cache.query.handler.ts
네네 생각보다 수정사항이 많더라구요..

2024-01-31 05:07 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistent/indicator-board-meta-data.persistent.adapter.ts
> +    const indicatorBoardMetaDataEntity: IndicatorBoardMetaDataEntity = IndicatorBoardMetaDataMapper.mapToEntity(
이러면 좀더 domain이랑 entity가 분리된거 같아서 이런시긍로 했는데 사실 큰 의미는 없는거 같아 변경하겠습니다

2024-01-31 07:56 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistent/indicator-board-meta-data.persistent.adapter.ts
> +    const indicatorBoardMetaDataEntity: IndicatorBoardMetaDataEntity = IndicatorBoardMetaDataMapper.mapToEntity(
[4167b52](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/4167b52d78ea3e36ba95159e260f6c965699d0c6)

2024-01-31 07:56 UTC, Hoya324 commented on api/src/numerical-guidance/domain/rule/IndicatorBoardMetaData.rule.ts
> +export class IndicatorBoardMetaDataRule implements BusinessRule {
[0b48624](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/0b486247445c4aaa19c4c2b24a60c3ec1d15b9be)

2024-01-31 07:57 UTC, Hoya324 commented
> 5b5e405

[01b32d8](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/01b32d8ffa7a0e779408e3a67a6032cd20bde684)
[25c8eba](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/25c8ebaa1b71d9e0176c9e507f643106c96a1905)
[5b5e405](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/5b5e40509927e8b650740dc5ea7bc3b4c2a2fb23)


test 작성 완료했습니다

2024-02-01 05:02 UTC, seonghunYang commented on api/src/numerical-guidance/domain/rule/IndicatorBoardMetaDataMustNotBeEmpty.rule.ts
> +}
[request change]
- 이거 우리 생성할 때 빈깡통으로 만들어져서 지표 개수 0개로 보내줘야할꺼야 최손ㄴ 빼야할 듯
- 그리고 이렇게 2개를 검사하는거면 rule을 2개로 빼서 만들어줘야해

2024-02-01 05:06 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/persistent/indicator-board-meta-data.persistent.adapter.ts
> +      IndicatorBoardMetaDataMapper.mapToEntity(indicatorBoardMetaData);
이러면 map[이전 객체]toEntity로 함수명이 바뀌어야할 듯
여기서는 mapDomainToEntity가 적절할 듯

2024-02-01 05:08 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/query/create-indicator-board-meta-data.command.handler.spec.ts
[request change]
- 이거 query 폴더가 아니라 command 폴더로 가야합니다

2024-02-01 09:51 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistent/indicator-board-meta-data.persistent.adapter.ts
> +      IndicatorBoardMetaDataMapper.mapToEntity(indicatorBoardMetaData);
[f426155](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/f4261555f765e6ab8136cbaaea87a7f53f7a03cc)

2024-02-01 09:52 UTC, Hoya324 commented on api/src/numerical-guidance/domain/rule/IndicatorBoardMetaDataMustNotBeEmpty.rule.ts
> +}
[fe09f45](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/fe09f453a421fb4e3de48707c43ea713783fe6ef)

2024-02-01 09:52 UTC, Hoya324 commented on api/src/numerical-guidance/test/unit-test/query/create-indicator-board-meta-data.command.handler.spec.ts
[56c2863](https://github.com/Corporation-dok/ECONO-AI/pull/49/commits/56c28631ba205657638dd902a95ac5c412b9b893)

2024-02-02 02:05 UTC, seonghunYang requested changes

2024-02-02 02:05 UTC, seonghunYang commented on api/src/numerical-guidance/domain/rule/IndicatorBoardMetaDataMustNotBeEmpty.rule.ts
>    get Message() {
[request change]
- 최소값은 설정안해줘도 될 것 같아요. 처음에 생성할 때 지표가 빈값으로 갈거라서
- 최대개수 제한 rule로 변경해주세요

2024-02-02 02:05 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/domain/indicator-board-meta-data.spec.ts
> +  it('지표보드 메타데이터의 지표는 비어있지만, key값은 1개로 고정이다.', () => {
[request change]
여기도 rule 변경에 맞춰서 수정해주세요!
생각해보니 rule에 빈 이름값 체크하는 rule도 만들어서 그것까지 테스트해주세요!

2024-02-02 02:07 UTC, Hoya324 commented on api/src/numerical-guidance/test/unit-test/domain/indicator-board-meta-data.spec.ts
> +  it('지표보드 메타데이터의 지표는 비어있지만, key값은 1개로 고정이다.', () => {
지표보드 메타데이터 이름이 비어있으면 안 되는거죠??

2024-02-02 02:08 UTC, Hoya324 commented on api/src/numerical-guidance/domain/rule/IndicatorBoardMetaDataMustNotBeEmpty.rule.ts
>    get Message() {
최대개수는 일단 5개로 할까요? default가 5개이니 적합한거 같습니다

2024-02-02 05:53 UTC, seonghunYang approved these changes

2024-02-02 05:53 UTC, merged