Ei 112 get indicator list
Corporation-dok/ECONO-AI pull request #50
Opened 2024-01-30 16:46 UTC by yoounyoungheon

2024-01-31 10:19 UTC, seonghunYang requested changes
- 수고하셨습니다
- 우선 전반적인 구조는 어느정도 파악한거 같은데 아직 디테일한 요소들에서 이해가 부족한게 느껴집니다!
- 현실적으로 당연한것이고 늘리는게 중요한데, 저 한테 더 직접적으로 물어보셔도 좋을 것 같아요. 이건 왜 이렇게 한건지 좀 더 디테일하게 말이죠
- 제가 요청한 리뷰 하시다보면 막히는 부분이 생기실 것 같은데 그때 내일 저한테 바로 물어보세요! 일부로 그렇게 유도했습니다.
- seeding이 작동하는 원리가 코드만 보고서는 잘 모르겠네요 내일 코어타임 때 설명 부탁드려요

2024-01-31 10:19 UTC, seonghunYang commented on api/src/numerical-guidance/application/port/indicator-list/get-indicator-list.port.ts
> +export interface GetIndicatorListPort {
[request change]
get이 가장 적합한 네이밍일까요? 우리가 흔히 쓰는 get, post, put 같은 접두사는 http 요청 메소드로 특정 클라이언트와 서버 간 네트워크 통신시에 사용하는 단어입니다.
이 port 역할이 위와 같은 상황인지 아니라면 어떤 네이밍이 더 적합한지 고민해볼 필요가 있는 것 같아요

2024-01-31 10:19 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +    }
[request change]

- DTO에 create 정적 생성자 만들고 여기서는 왜 이렇게 처리하나요?
- 또 변환할 때 for문보다 .map() 과 같은 고차함수를 사용하면 더 좋을 것 같습니다

2024-01-31 10:19 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +  }
이건 왜 이렇게 한건가요?

2024-01-31 10:19 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/indicator-list/indicator-list.adapter.spec.ts
테스트에서 seeding이 작동하는 원리가 궁금하네요. 설명 부탁드려요

2024-02-01 04:11 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/api/numerical-guidance.controller.ts
> +  @Get('/get-indicator-list')
이거 camelCase로 하는게 어떤지 의견 궁금합니다 @seonghunYang

2024-02-01 17:10 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/port/indicator-list/get-indicator-list.port.ts
> +export interface GetIndicatorListPort {
7816c969e3b178f0f792bb0daf976b337b14be6e 
get대신 load를 사용했습니다 !

2024-02-01 17:13 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +    }
6246a576490b7e748356f8e634fbbc209564a7ed
adapter에서 정적 생성자 만들어서 처리하도록 수정했습니다 !
데이터 변환 시 map()함수를 사용하는 방식으로 수정했습니다. 앞으로는 고차함수를 사용하는 방식을 공부하며 적용해보겠습니다 !

2024-02-02 01:53 UTC, seonghunYang requested changes

2024-02-02 01:53 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +    });
[request change]
커뮤니티 모듈에서 저렇게 작성한 이유는 mock을 위해서 일부로 지연을 주기 위해서 작성한 겁니다.
해당 코드는 비동기랑은 상관 없어요! 수정 부탁드립니다.
설명 필요하시면 코어 타임 때 말씀해주세요 :)

2024-02-02 01:53 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/api/numerical-guidance.controller.ts
> +  @Get('/get-indicator-list')
https://www.rocketpunch.com/cards/post/436146
https://velog.io/@caesars000/RESTful-API-%EA%B0%80%EC%9D%B4%EB%93%9C
 - 이건 코어타임 때 좀 더 논의해봅시다

2024-02-02 01:57 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +    }
- 이렇게하면 사실상 create의 의미가 없어지니까 저 map 로직을 create 내부로 빼는게 어떨까요?
- 고차 함수는 선언형 프로그래밍이라는 중요한 패러다임이랑 연관되니까 공부하시면 좋아요!

2024-02-02 01:59 UTC, seonghunYang requested changes

2024-02-02 01:59 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +
[request change]
- 이렇게하면 사실상 create의 의미가 없어지니까 저 map 로직을 create 내부로 빼는게 어떨까요?
- 고차 함수는 선언형 프로그래밍이라는 중요한 패러다임이랑 연관되니까 공부하시면 좋아요!

2024-02-02 01:59 UTC, seonghunYang commented on api/package.json
> +    "pretest": "ts-node -r tsconfig-paths/register ./node_modules/typeorm-extension/bin/cli.cjs seed:run -d ./src/database/seeds/dataSource.ts",
[comment] 
좋네요! 이건 jest가 제공하는 기능인가요?

2024-02-02 03:59 UTC, yoounyoungheon commented on api/package.json
> +    "pretest": "ts-node -r tsconfig-paths/register ./node_modules/typeorm-extension/bin/cli.cjs seed:run -d ./src/database/seeds/dataSource.ts",
57983a7d4bddef37e7c52f7b8644d31f4701d033
package.json에서 scripts 작성할 때 제공하는 기능입니다 !

2024-02-02 17:21 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +
b8d4baec4a1ec0aa0309310022062715285c72d0
postgres으 환경에 맞춰 seeding 변경하는데 집중해서 늦었습니다. 죄송합니다..

2024-02-02 17:23 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +    });
c9a52298c775da95ccf5959a12e147b5baa51ef6
수정했습니다!

2024-02-03 04:08 UTC, seonghunYang requested changes

2024-02-03 04:08 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/indicator-list.adapter.ts
> +    });
- 저  map 하는 로직을 create 함수 내부로 감추면 어떻겠냐는 말이었습니다 ! 
- 생성 로직이 지금 create 밖에 있는데 create 함수 내에서 생성 로직을 작성하는게 좋아보여요

2024-02-03 07:38 UTC, seonghunYang requested changes

2024-02-03 07:38 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/mapper/indicator-list.mapper.ts
> +}
이미 IndicatorList에 어떤 데이터인지 드러났기 때문에 mapDomainToEntity 이런식으로 어떤 객체로 변환하는지만 서술하면 될 것 같습니다

2024-02-03 07:47 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/indicator-list/mapper/indicator-list.mapper.ts
> +}
451a570921b1b71c94c0cc8f6fb654bda70c8041
이름 수정했습니다!

2024-02-03 07:49 UTC, seonghunYang approved these changes

2024-02-03 07:49 UTC, merged