Ei 95
Corporation-dok/ECONO-AI pull request #76
Opened 2024-02-12 16:18 UTC by yoounyoungheon

✅ 작업 내용
- **exception-filter 계층 구현**
   애플리케이션 코드에서 처리하지 않는 예외를 포착하여 사용자 친화적인 응답을 자동으로 보내는 계층
   원하는 곳에 exception-filter를 연결해서 사용
   parameter: exception(현재 처리 중인 예외 객체), Argumentshost(핸들러에 전달되는 인수를 검색하는 메서드)
- 메타 데이터 id값을 가지고 메타 데이터를 가져오는 api 구현
- id 값에 해당하는 메타데이터가 없을 경우 error 메세지를 보내도록 adapter에서 처리

## 🤔 고민 했던 부분
- id값에 해당하는 메타데이터가 없을 경우 에러처리를 어디서 해야할지 고민했습니다. db관련 로직을 처리하는 adapter에서 해당 에러를 처리하도록 했고, adpter 통합 테스트에서 예외처리 테스트 코드를 작성했습니다.

## 🔊 도움이 필요한 부분
- exception-filter에 대한 설명을 들으신 수 조금 더 보완이 필요한 점을 말해주시면 감사하겠습니다.

2024-02-13 04:12 UTC, seonghunYang requested changes

2024-02-13 04:12 UTC, seonghunYang commented on api/src/numerical-guidance/api/numerical-guidance.controller.ts
> +  @UseFilters(new HttpExceptionFilter())
[comment]
- 위에서 글로벌로 적용했는데 여기에 또 적어줘야하나요?

2024-02-13 04:12 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
> +    try {
[request change]
- what: 에러 테스트 방법 수정
- why: 더 나은 테스트 코드 품질를 위해서
- description: jest로 에러 검증 시에 2가지 방법이 있는 것으로 압니다. 영헌씨가 작성해주신 try ~catch가 있고 expect로 처리하는 방법이 있는데 저는 후자가 좀 더 적합하다고 생각해서 수정을 제안합니다. 이유는 아래 첨부한 링크를 참고해주세요!
https://jojoldu.tistory.com/656

2024-02-13 04:12 UTC, seonghunYang commented on api/src/utils/exception-filter/execptionFilter.ts
[comment]
- 기존에 nest에서 제공하는 default 에러 필터랑 어떤 차이점이 있는지 설명해주세요!

2024-02-13 04:12 UTC, seonghunYang commented on api/src/utils/exception-filter/execptionFilter.ts
> +
[commemt]
- error 타입이 string 일때와 아닐 때 차이가 무엇인가요?

2024-02-13 05:16 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
> +    try {
014fe713a1073dca02fca1e9823b22e68451cd06
수정했습니다!

2024-02-13 05:16 UTC, yoounyoungheon commented on api/src/numerical-guidance/api/numerical-guidance.controller.ts
> +  @UseFilters(new HttpExceptionFilter())
e67d37b871bf375875e4acab74bf83759ea8f0f1
수정했습니다!

2024-02-13 05:34 UTC, yoounyoungheon commented on api/src/utils/exception-filter/execptionFilter.ts
> +
위에서 말한것 과 같이 error타입이 string일 경우 object로 오는 객체가 undifined인 경우가 있어서, 서치해보니 error타입을 여러 방식으로 지정해두면 보다 상세한 정보를 클라이언트에게 보낼 수 있었습니다 !

2024-02-13 05:34 UTC, yoounyoungheon commented on api/src/utils/exception-filter/execptionFilter.ts
1. log추가: console에 log를 추가해서 에러 추적을 용이하게 해줌
2. 에러가 string이 아닌 다른 객체인 경우까지 다른 JSON schema를 사용하여 response값으로 반환해 client에게 보다 정확한 흐름을 제공할 수 있음(우리 서비스에서는 상세한 에러 정보 제공)

2024-02-13 05:52 UTC, seonghunYang commented on api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
> +    try {
커밋에 수정 요청 남겨놨습니다!

2024-02-13 05:55 UTC, seonghunYang commented on api/src/utils/exception-filter/execptionFilter.ts
추가로 궁금한 점이 있어서 질문 드립니다. 저희가 따로 에러 계층을 만들면 nest 디폴트 에러 계층은 사라지나요 아니면 여전히 존재하나요?

2024-02-13 05:58 UTC, seonghunYang requested changes

2024-02-13 05:58 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +
[requset change]
- what: 에러타입 수정 요청
- why: 더 명확한 표현 및 개발 편의성을 위해
- description: nest에서 HttpException외에도 내장으로 제공하는 error 객체가 있습니다. 이걸 사용하는게 더 의도를 잘표현할 것 같네요. 아래 링크를 참고해서 수정부탁드릴게요!
https://docs.nestjs.com/exception-filters#built-in-http-exceptions

2024-02-13 06:01 UTC, yoounyoungheon commented on api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
> +    try {
103f7e2be2000acaee33cd30aa3ba1cf025aeaff

2024-02-13 06:19 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +
f2bb2b2bb398a5220af357be8a5a922da4ee3192
수정했습니다!
다만 BadRequestException의 파라미터인 description은 string 객체만 담을 수 있어서 Error객체를 담기위해서 descriptoin대신 error를 파라미터로 줬습니다.

2024-02-13 06:53 UTC, yoounyoungheon commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +
f50c4ce254ab96d29083ea681651208019e2a144
BadRequestException, HttpExceptoin 등 모든 예외처리에대한 global-error filter로 수정했습니다 !

2024-02-13 06:57 UTC, yoounyoungheon commented on api/src/utils/exception-filter/execptionFilter.ts
"Typically, you'll create fully customized exception filters crafted to fulfill your application requirements. However, there might be use-cases when you would like to simply extend the built-in default global exception filter, and override the behavior based on certain factors." 공식문서에 나와있는 설명인데 default filter를 확장할 뿐 사라지지는 않는 것 같습니다!

2024-02-13 07:09 UTC, seonghunYang reviewed
1. http 전용 에러 필터 만들기, 여기서 처리 못하는건 디폴트 에러 필터에서 처리
2. 에러 instance 마다 다른 에러 처리 로직을 붙일 수 있도록 구성
3. 전체적인 리팩토링

2024-02-14 07:01 UTC, seonghunYang approved these changes

2024-02-14 07:01 UTC, merged