Ei 136
Corporation-dok/ECONO-AI pull request #82
Opened 2024-02-16 04:59 UTC by yoounyoungheon

✅ 작업 내용
- 지표 리스트에 "market"을 추가했습니다.
- Entity에는 nullable option을 추가했습니다.

## 🤔 고민 했던 부분

## 🔊 도움이 필요한 부분

2024-02-16 13:32 UTC, seonghunYang requested changes
types에 type은 조금 아쉬운 네이밍인 것 같아요. 아마 market 타입만 있어서 그런 것 같은데
market 처럼 공통적으로 쓰이는 타입을 찾아서 리팩토링해보면 더 명확하게 드러나지 않을까요? 리팩토링까지 하면 코드도 더 깔끔해지고 좋을 것 같아요 부탁드려요!

2024-02-17 06:47 UTC, yoounyoungheon commented
40be614274eac135bf30fed3f9405f29505049f0
IndicatorType, Market, Interval에 대한 type을 정의했습니다.

2024-02-17 06:49 UTC, yoounyoungheon commented
36d680a8bd7ef1237268a777def5e358daceaf06
IsMarket validation을 추가해서 controller에서 검증하도록 수정했습니다.

2024-02-17 06:49 UTC, yoounyoungheon commented
298e2a14d1590dd53a6e885352fc059b27f3800b
파일명을 type-definition으로 수정했습니다

2024-02-17 06:54 UTC, seonghunYang commented
> [36d680a](https://github.com/Corporation-dok/ECONO-AI/commit/36d680a8bd7ef1237268a777def5e358daceaf06) IsMarket validation을 추가해서 controller에서 검증하도록 수정했습니다.

좋네요!!

2024-02-17 06:55 UTC, seonghunYang submitted a review, later dismissed
- 수고하셨습니다. 처음 pr 보다 훨씬 좋아졌네요
- 특히 validation 추가하신 것 같은 액션이 더 많아지면 더 좋은 코드가 나올 것 같아요

2024-02-17 07:43 UTC, merged