[Ei-132] 지표보드 메타데이터에 지표 추가
Corporation-dok/ECONO-AI pull request #84
Opened 2024-02-16 13:05 UTC by Hoya324

✅ 작업 내용
- 지표보드 메타데이터에 지표 추가하는 작업을 진행했습니다.
- 지표보드 메타데이터를 초기 생성할 때,  tickers를 빈값으로 생성해주도록 변경했습니다.

## 🤔 고민 했던 부분
- 지표를 추가하는 계층이 어디여야하는지 고민되었고, domain에서 일어나야한다는 것으로 결론지었습니다. 즉, 도메인 계층에서 핵심적인 로직이 이뤄져야한다는 점을 재확인했습니다.
 
## 🔊 도움이 필요한 부분
- 추가해야할 도메인 로직 있다면 편하게 말씀해주세요!

2024-02-16 13:30 UTC, seonghunYang requested changes

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/application/command/insert-indicator-ticker/insert-indicator-ticker.command.handler.ts
> +}
완벽합니다 굿굿

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/domain/indicator-board-metadata.ts
> +    }
[request change]
- 여기 부분 코드 좀 더 개선할 수 있는 여지가 보여요! 
- 한번 리팩토링 해보시겠어요?

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/domain/indicator-board-metadata.ts
> +      const indicatorTickers: string[] = newTickers[type]?.toString().split(',');
[comment]
여기 이해가 살짝 안가는데 string[]타입을 왜 다시 string 으로 만들고 분할하나요? 설마 값이
["ㄴㅇㅁ", "ㄴㅁㅇ", "ㄴㅁㅇ"] 이렇게 오나요?

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/domain/indicator-board-metadata.ts
> +  }
여기 부분 아릅답네요 굿

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/domain/rule/IndicatorBoardMetaDataNameShouldNotEmpty.rule.ts
> +    this.indicatorBoardMetaDataName.trim() === '' ||
[comment]
- 이거 결국 어캐 되었나요?

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +      });
[request change]
- error 의도가 더 명확하게 드러나야 해요
- 우선 bad request가 맞나요? db 오류 일 수 있지 않을까요?
- 만약 bad request라고 할지라도 어떤 값 때문에 오류가 났는지를 메시지에 전달해야 BE 오류 계층에서든 FE에서든 처리를 해줄 수 있어요!

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/test/E2E test/nemerical-guidance.e2e.spec.ts
[request change]
- 비즈니스 규칙에 위반되는 경우에 대한 e2e 테스트도 작성하는게 좋을 거 같아요. 전부 할 필요는 없고 하나 정도해서 비즈니스 규칙을 위반하면 어떤 응답이 오는지 테스트 해봅시다

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/domain/indicator-board-metadata.spec.ts
도메인 객체에 대한 테스트가 많아서 좋네요

2024-02-16 13:30 UTC, seonghunYang commented on api/src/numerical-guidance/test/unit-test/command/insert-indicator-ticker.command.handler.spec.ts
[comment]
도메인 객체와 비슷한 테스트일 것 같긴 하지만 통합테스트보다 애플리케이션 계층의 테스트 코드가 적은건 아쉽네요. 아마 에러가 나도 핸들러에서 처리하지 않고 예외 필터 계층에서 처리하기 때문일까요? 
한번 정도 애플리케이션 계층에 어떤 테스트를 할 수 있을지 고민해보면 좋을 것 같아요

2024-02-16 13:33 UTC, seonghunYang commented
전체적으로 훌륭해요. 아까 디코로 이야기 한 의도를 제대로 파악한 것 같아서 기분이 좋네요. 몇가지 수정사항을 올렸으니 시간 구애 받지 말고 고민해보고 반영부탁드려요.

2024-02-16 13:44 UTC, Hoya324 commented on api/src/numerical-guidance/domain/indicator-board-metadata.ts
> +      const indicatorTickers: string[] = newTickers[type]?.toString().split(',');
newTickers[type] 이것만 하면 값이 오류가 생기더라고요.. 그래서 아예 string으로 만들고 리스트로 바꿔버린겁니다! ["ㄴㅇㅁ", "ㄴㅁㅇ", "ㄴㅁㅇ"] 처럼 string[] 식으로 오는게 맞는데 배열 메서드가 안 먹습니다ㅠㅠ

2024-02-16 13:45 UTC, Hoya324 commented on api/src/numerical-guidance/domain/rule/IndicatorBoardMetaDataNameShouldNotEmpty.rule.ts
> +    this.indicatorBoardMetaDataName.trim() === '' ||
이거 규칙 변경하면서 조건문에 실수를 했더라구요..ㅎㅎ 남탓하지 않기로 했습니다,,

2024-02-16 13:45 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +      });
예외 부분을 좀더 세분화해보겠습니다!

2024-02-16 13:49 UTC, Hoya324 commented on api/src/numerical-guidance/test/unit-test/command/insert-indicator-ticker.command.handler.spec.ts
도메인에 잘 접근하고 있는지 테스트해보면 좋을 듯 하네요

2024-02-16 14:19 UTC, Hoya324 commented on api/src/numerical-guidance/domain/indicator-board-metadata.ts
> +    }
[75b6f3f](https://github.com/Corporation-dok/ECONO-AI/pull/84/commits/75b6f3f0800325e74a4fc8c430c452b3696437e2)

2024-02-16 14:19 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +      });
[0eb7d8a](https://github.com/Corporation-dok/ECONO-AI/pull/84/commits/0eb7d8afa38fc0061e081107af081a7597618ac4)

2024-02-17 05:45 UTC, Hoya324 commented on api/src/numerical-guidance/domain/indicator-board-metadata.ts
> +    }
[2590e90](https://github.com/Corporation-dok/ECONO-AI/pull/84/commits/2590e908d5349b92245821ec5d6eb055dc0f8dae)

위 방법으로 하려했는데 조건이 알맞게 처리가 안 돼서 조건을 따로 뺐습니다

2024-02-17 05:45 UTC, Hoya324 commented on api/src/numerical-guidance/test/E2E test/nemerical-guidance.e2e.spec.ts
[44aa93c](https://github.com/Corporation-dok/ECONO-AI/pull/84/commits/44aa93ccc51e39311e7aabdcce309068e2d2bbbe)

2024-02-17 07:12 UTC, seonghunYang commented on api/src/numerical-guidance/domain/indicator-board-metadata.ts
> +    }
- 좋네요! 처음보다 훨씬 보기 좋습니다

2024-02-17 07:22 UTC, seonghunYang approved these changes

2024-02-17 07:22 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +    }
[request change]
- 에러 처리가 훨씬 세분화 되어서 좋네요
- 근데 에러 메시지만 보고도 이게 무슨 문제인지 바로 파악할 수 있도록 해야 디버깅시에도 그리고 에러 처리할 때도 유용해요
- https://toss.tech/article/engineering-note-2 토스 기술 블로그인데 해결 1단계: 로그에 맥락 남기기 여기 예제코드 처럼 어떤 상황 에러인지 좀 더 명확해야합니다. '[ERROR] 지표보드 메타데이터를 생성하는 도중에 오류가 발생했습니다.', 이 문장만 보고는 어떤 문제가 있는지 드러나지 않는 것 같아요. 
- 실제로 badrequest가 동작할 포인트가 그리고 있나요? 밑에 테스트 보니까 memberId가 이상하면 Notfound가 동작하는건가요 badrequest가 동작하는 건가요?

2024-02-17 07:22 UTC, seonghunYang commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +    }
[request change]
- 위처럼 에러 메시지가 좀 더 명확해져야하고
- 각 에러 상황에 대한 테스트가 이뤄져야합니다
- 생각해봤는데 기준을 잡을 때 테스트가  가능할 때 에러 분기처리를 하면 좋겠네요!

2024-02-17 07:23 UTC, seonghunYang commented
- 에러처리는 생각보다 크게 중요한 부분이에요.
- 서비스의 성숙도와 완성도는 정상경로보다 생각보다 에러처리 부분에서 나온답니다.
- 그만큼 시간을 들일 가치가 있는 곳이다보니 리뷰 남긴 부분 고민해서 수정 반영해주세요!

2024-02-17 09:27 UTC, seonghunYang requested changes
에러처리는 생각보다 크게 중요한 부분이에요.
서비스의 성숙도와 완성도는 정상경로보다 생각보다 에러처리 부분에서 나온답니다.
그만큼 시간을 들일 가치가 있는 곳이다보니 리뷰 남긴 부분 고민해서 수정 반영해주세요!

2024-02-17 16:19 UTC, Hoya324 commented on api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
> +    }
[8bcf921](https://github.com/Corporation-dok/ECONO-AI/pull/84/commits/8bcf921488a9f81d63ec66145ea337b1897a6d59)
[fa34049](https://github.com/Corporation-dok/ECONO-AI/pull/84/commits/fa34049f82cf5dc6478b62a7b1ed9d75e56785d9)

좀더 명확하게 처리하고, 테스트도 추가했는데, 이 부분 중요한거 같다는 생각이 들어서, 필요한 예외처리에 대해 함께 논의해보면 좋을거 같습니다

2024-02-18 03:09 UTC, seonghunYang approved these changes
- 수고하셨습니다. 에러 처리 부분이 훨씬 정리되고 의도가 드러나는 것 같네요!

2024-02-18 03:25 UTC, merged